package in.hashconnect.gmb.vo;

public enum Metric {
	
	METRIC_UNSPECIFIED,
	ALL,QUERIES_DIRECT,QUERIES_INDIRECT,QUERIES_CHAIN,
	VIEWS_MAPS,VIEWS_SEARCH,ACTIONS_WEBSITE,ACTIONS_PHONE,
	ACTIONS_DRIVING_DIRECTIONS,PHOTOS_VIEWS_MERCHANT,PHOTOS_VIEWS_CUSTOMERS,
	PHOTOS_COUNT_MERCHANT,PHOTOS_COUNT_CUSTOMERS,LOCAL_POST_VIEWS_SEARCH,
	LOCAL_POST_ACTIONS_CALL_TO_ACTION
}
