pipeline {
    agent any
    tools {
        git 'gitRepo'
        maven 'Maven-3.9.6'
        jdk 'Java-17'
    }

    environment {
        GITLAB_PACKAGE_URL = "https://gitlab-hc.hashconnect.in/api/v4/projects/226/packages/maven"
        GITLAB_TOKEN = credentials('shekar-hash') // Use the ID of the GitLab token credential
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'shekar-hash', url: 'https://gitlab-hc.hashconnect.in/hashconnect/platform.git'
            }
        }

        stage('Build') {
            steps {
                echo "Starting build ...."
                sh '''
                export MAVEN_OPTS=-Dmaven.multiModuleProjectDirectory
                mvn clean install
                '''
                echo "Build Success.."
            }
        }

        stage('Publish to GitLab Package Registry') {
            steps {
                echo "Publishing artifact to GitLab package registry ..."
                sh '''
                mvn deploy -s settings.xml
                '''
                echo "Artifact published successfully!"
            }
        }
        
    }

    post {
        success {
            echo "Pipeline completed successfully!"
        }
        failure {
            echo "Pipeline failed."
        }
    }
}
